# -*- coding: utf-8 -*-
"""Declaración.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLyJyOuit9pTI9ooloP3YxHDmyqpMFz_
"""

# app.py

import streamlit as st
import pdfplumber
import pandas as pd
import json
from openai import OpenAI

# -----------------------------------
# CONFIGURACIÓN OPENAI
# -----------------------------------

client = OpenAI(
    api_key="TU_API_KEY_OPENAI"
)

# -----------------------------------
# CONFIG STREAMLIT
# -----------------------------------

st.set_page_config(
    page_title="Asistente Fiscal SAT",
    layout="wide"
)

st.title("📄 Asistente Fiscal SAT")
st.write("Sube constancias fiscales de CETES Directo o GBM")

# -----------------------------------
# SUBIR ARCHIVO
# -----------------------------------

uploaded_file = st.file_uploader(
    "Sube tu constancia PDF",
    type=["pdf"]
)

# -----------------------------------
# EXTRAER TEXTO PDF
# -----------------------------------

def extraer_texto_pdf(pdf_file):

    texto = ""

    with pdfplumber.open(pdf_file) as pdf:

        for page in pdf.pages:

            contenido = page.extract_text()

            if contenido:
                texto += contenido + "\n"

    return texto

# -----------------------------------
# ANALIZAR CON OPENAI
# -----------------------------------

def analizar_constancia(texto):

    prompt = f"""
    Analiza la siguiente constancia fiscal mexicana.

    Extrae los conceptos fiscales relevantes y clasifícalos:

    - acumulable
    - acreditable
    - no acumulable

    Busca especialmente:

    - interés nominal
    - interés real
    - ISR retenido
    - resultado fiscal fibras
    - reembolso de capital
    - dividendos
    - pérdidas

    Devuelve SOLO JSON válido.

    Formato esperado:

    {{
        "conceptos":[
            {{
                "concepto":"Interés Real",
                "monto":4226.54,
                "tratamiento":"acumulable"
            }}
        ],
        "resumen": {{
            "ingreso_acumulable": 0,
            "isr_acreditable": 0,
            "no_acumulable": 0
        }}
    }}

    CONSTANCIA:

    {texto}
    """

    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[
            {
                "role": "system",
                "content": "Eres un experto fiscal mexicano especializado en SAT, CETES, GBM y FIBRAS."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    contenido = response.choices[0].message.content

    return contenido

# -----------------------------------
# PROCESAR ARCHIVO
# -----------------------------------

if uploaded_file is not None:

    st.success("PDF cargado correctamente")

    with st.spinner("Extrayendo texto..."):

        texto_pdf = extraer_texto_pdf(uploaded_file)

    st.subheader("📑 Texto Detectado")

    st.text_area(
        "Contenido PDF",
        texto_pdf,
        height=250
    )

    if st.button("Analizar Constancia"):

        with st.spinner("Analizando información fiscal..."):

            resultado = analizar_constancia(texto_pdf)

        st.subheader("📊 Resultado Fiscal")

        try:

            datos = json.loads(resultado)

            # -----------------------------------
            # TABLA CONCEPTOS
            # -----------------------------------

            conceptos = datos["conceptos"]

            df = pd.DataFrame(conceptos)

            st.dataframe(
                df,
                use_container_width=True
            )

            # -----------------------------------
            # RESUMEN
            # -----------------------------------

            resumen = datos["resumen"]

            st.subheader("🧾 Resumen SAT")

            col1, col2, col3 = st.columns(3)

            col1.metric(
                "Ingreso Acumulable",
                f"${resumen['ingreso_acumulable']:,.2f}"
            )

            col2.metric(
                "ISR Acreditable",
                f"${resumen['isr_acreditable']:,.2f}"
            )

            col3.metric(
                "No Acumulable",
                f"${resumen['no_acumulable']:,.2f}"
            )

            # -----------------------------------
            # DESCARGA EXCEL
            # -----------------------------------

            excel_file = "resultado_fiscal.xlsx"

            with pd.ExcelWriter(excel_file) as writer:

                df.to_excel(
                    writer,
                    index=False,
                    sheet_name="Conceptos"
                )

            with open(excel_file, "rb") as f:

                st.download_button(
                    label="⬇ Descargar Excel",
                    data=f,
                    file_name="resultado_fiscal.xlsx",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                )

        except Exception as e:

            st.error("Error procesando JSON")

            st.write(resultado)

            st.write(e)